-- AralLoop Campus - Supabase schema
-- Run in Supabase SQL Editor before deploying the frontend.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  role text not null default 'Student',
  course text,
  created_at timestamptz not null default now()
);

create table if not exists public.app_states (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.app_states enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can read own state" on public.app_states;
create policy "Users can read own state"
on public.app_states for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own state" on public.app_states;
create policy "Users can insert own state"
on public.app_states for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own state" on public.app_states;
create policy "Users can update own state"
on public.app_states for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own state" on public.app_states;
create policy "Users can delete own state"
on public.app_states for delete
to authenticated
using (auth.uid() = user_id);

-- Role and CMS extension (AralLoop v2)
alter table public.profiles add column if not exists active boolean not null default true;
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('Student','Teacher','Admin'));
create table if not exists public.cms_content (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('announcement','resource','faq')),
  title text not null, body text not null,
  audience text not null default 'all' check (audience in ('all','student','teacher')),
  status text not null default 'draft' check (status in ('draft','published')),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.cms_content enable row level security;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.profiles p where p.id = auth.uid() and p.role = 'Admin' and p.active = true); $$;
drop policy if exists "Published CMS content is readable" on public.cms_content;
create policy "Published CMS content is readable" on public.cms_content for select to authenticated using (status = 'published' or public.is_admin());
drop policy if exists "Admins manage CMS content" on public.cms_content;
create policy "Admins manage CMS content" on public.cms_content for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admins can read profiles" on public.profiles;
create policy "Admins can read profiles" on public.profiles for select to authenticated using (auth.uid() = id or public.is_admin());

-- AralLoop v3 portal security -------------------------------------------------
-- Public registration may create only Student profiles. Teacher elevation is
-- performed by the server-side function below after validating the teacher code.
-- The code is intentionally stored in database/server SQL rather than browser JS.

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own student profile"
on public.profiles for insert to authenticated
with check (auth.uid() = id and role = 'Student');

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own non-role profile"
on public.profiles for update to authenticated
using (auth.uid() = id)
with check (
  auth.uid() = id
  and role = (select p.role from public.profiles p where p.id = auth.uid())
);

create or replace function public.claim_teacher_role(teacher_code text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;
  if teacher_code <> 'PUPTEACHER2026' then
    return false;
  end if;
  update public.profiles set role = 'Teacher', active = true where id = auth.uid();
  return found;
end;
$$;
revoke all on function public.claim_teacher_role(text) from public;
grant execute on function public.claim_teacher_role(text) to authenticated;


-- AralLoop v4 Admin portal access code ---------------------------------------
-- This is an additional classroom-prototype check. The Admin role and RLS
-- remain the actual authorization boundary. Never place this code in browser JS.
create or replace function public.verify_admin_access_code(admin_code text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;
  if not public.is_admin() then
    return false;
  end if;
  return admin_code = 'PUPADMIN2026';
end;
$$;
revoke all on function public.verify_admin_access_code(text) from public;
grant execute on function public.verify_admin_access_code(text) to authenticated;
